### ISSUE TITLE
[Bug] Error when comparing date types in google_play__finance_report

### ISSUE THREAD

**Issue by casparwylie** [fivetran/dbt_google_play#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When running the dbt model `google_play__finance_report`, the line `on earnings.date_day = subscriptions.date_day` causes issues because `financial_stats_subscriptions_country.date` and `earnings.transaction_date` are being compared, but are different types. 

STRING -> DATE casting happens for `earnings.transaction_date` in `google_play_source/models/stg_google_play__earnings.sql`, but `financial_stats_subscriptions_country.date` is a TIMESTAMP.

This is presumably related to recent Fivetran changes. 

### Relevant error log or model output

```shell
Database Error in model google_play__finance_report (models/google_play__finance_report.sql)
  No matching signature for operator = for argument types: DATE, TIMESTAMP. Supported signature: ANY = ANY at [122:12]
```

### Expected behavior

Both fields should be the same data type so that the comparison works.

### dbt Project configurations

N/A

### Package versions

packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.1

  - package: fivetran/google_play
    version: [">=0.3.0", "<0.4.0"]

### What database are you using dbt with?

bigquery

### dbt Version

1.5.0

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
Hi there @casparwylie, thanks for taking the time to open this! 

I think it would be best to cast `date_day` as a `date` in the staging layer to ensure all the downstream joins run smoothly. In this case specifically, we'd update this [line](https://github.com/fivetran/dbt_google_play_source/blob/main/models/stg_google_play__subscriptions_country.sql#L26) to be `cast(date as date) as date_day`

Since all of the other staging models also have `date`/`date_dat` columns that are used for joins downstream, we should proactively add the type casts across the board.

With that in mind, would you still be interested in opening a PR? If you are still interested, we would happily welcome your PR and our team will prioritize its review once it comes through. Let me know if you are still interested or if you have any questions around opening a PR. Thanks!

**Comment by casparwylie** [comment]
Thanks Jamie. Here is a PR with the fixes https://github.com/fivetran/dbt_google_play_source/pull/12 .

PS. I'm unsure whether or not to keep my editor's choice the remove the unneeded whitespace...!

**Comment by casparwylie** [comment]
Any update on this?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @casparwylie apologies for the delay. There were some other updates we had to prioritize in the last week. We will be sure to get your PR reviewed and rolled out before the end of the week.

**Comment by fivetran-catfritz** [comment]
Hi @casparwylie I reviewing your PR and getting it ready for release. Also so you are aware, I am going to push some small updates like documentation and internal updates to your branch before merging into our main branch.

**Comment by casparwylie** [comment]
Excellent. Thank you!

**Comment by casparwylie** [comment]
Has this been merged somewhere else? (The PR is still open https://github.com/fivetran/dbt_google_play_source/pull/12)

**Comment by fivetran-catfritz** [comment]
@casparwylie Great timing! This is scheduled to be merged and released today.
